# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce5925f4bccc7cd664f6ce30de77d7203ca5c4462f311d536ee7101300fbb4d212ecbccb5d10c615ff18c4a22c7326b29dadd906b7174473e491ced7839470d

test:
  secret_key_base: 44a58e02c2cf55023a5ed17b52443007a7368fe5fa843fa06a0b8ee3bcd33a4b152ae4770a8c4b4258bc837dd6c3645119beb9b11792ef27183e195d6c8fb67d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
